name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
#
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and Test with Maven
        run: mvn -f simple-api/pom.xml clean verify
